### PR TITLE
[Ready] Allow refs

### PR DESCRIPTION
**Pull request by Gerschtli**
This PR allows that the `err`, `has`, `none`, `ok` and `some` matchers accept references in `assert_that!` macro. This simplifies multiple assertions on the same instance without the need to clone it.

I have added an editorconfigfile too. If you would like to have that in a separate PR, I will split it.

---
This change is [Reviewable](https://reviewable.io/reviews/valloric/hamcrest2-rust/6)

### CODE REVIEW

**Comment by asomers** [comment]
I think this would solve my problem.  However, why limit the new functionality to just those 5 matchers?  I think every `Matcher` should be able to match by reference.

**Comment by Gerschtli** [comment]
Yes, you are correct. And for completness there should also be a matcher for the mutable references. I will add these if I got some time!

Maybe there is a more generic way to solve this, but I didn't come up with any.

**Comment by asomers** [comment]
I tried to solve this generically by wrapping `HamcrestMatcher` with my own trait like this:
```rust
pub trait MyMatcher<I> {
    fn matches(&self, actual: &I) -> hamcrest2::core::MatchResult;
}
impl<'a, I, M> MyMatcher<I> for M where M: HamcrestMatcher<&'a I> {
    fn matches(&self, actual: &I) -> hamcrest2::core::MatchResult {
        HamcrestMatcher::matches(self, actual)
    }
}
```
However, that doesn't work because of lifetime issues.  I have to parameterize `MyMatcher` on `'a`, which makes it unnecessarily non-'`static`.  I couldn't find a way around that.  Right now I'm investigating the predicates crate as an alternative.  It defines the match function in terms of references, but has problems of its own.

**Comment by Gerschtli** [comment]
Does this work? Because you are actually giving a reference to the `HamcrestMatcher`

**Comment by asomers** [comment]
It would work.  But as I said the problem is that my matcher became non-`'static`.  For my application, that's a non-starter.

**Comment by Gerschtli** [comment]
https://doc.rust-lang.org/std/borrow/trait.Borrow.html seems to be the solution, I am trying to use this trait on all matchers, still WIP.

**Comment by Valloric** [comment]
@Gerschtli Huge apologies for this PR somehow falling off my radar; not sure how that happened! Again, really sorry. 

Thanks a ton for working on this!

I like what this PR is trying to achieve; I see from your latest comment that this is still WIP, so perhaps prefix the PR title with `[WIP]` and replace it with `[READY]` once it's ready to review (we use this approach on ycmd and YCM repos).

**Review by Valloric — APPROVED** [review]
Also fine with the `editorconfig` file.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/valloric/hamcrest2-rust/6#-:-LYV-sM0-5VJFt4UB0gJ:b-vhmj2e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Valloric** [comment]
Also, since I messed up so badly by not noticing this PR _for a whole month_ (mostly by being away from GitHub due to personal stuff), I'm just going to keep it open in a browser tab to reduce the odds of missing updates.

**Comment by Gerschtli** [comment]
I completed my work, but I skipped the `has` matcher intentionally, because of type problems. Personally, I don't see the reason, why this matcher exists.. Maybe it should be marked deprecated in favor of `some` and `ok`.

**Comment by Valloric** [comment]
Thanks for working on this! Looks great.

Seems that the Travis build failed on `cargo fmt`. Here's the problem it found:
```
Diff in /home/travis/build/Valloric/hamcrest2-rust/src/matchers/compared_to.rs at line 46:
     let it_succeeded = match self.operation {
       CompareOperation::LessOrEqual => actual_borrowed <= &self.right_hand_side,
       CompareOperation::LessThan => actual_borrowed < &self.right_hand_side,
-      CompareOperation::GreaterOrEqual => actual_borrowed >= &self.right_hand_side,
+      CompareOperation::GreaterOrEqual => {
+        actual_borrowed >= &self.right_hand_side
+      }
       CompareOperation::GreaterThan => actual_borrowed > &self.right_hand_side,
     };
 
Diff in /home/travis/build/Valloric/hamcrest2-rust/src/matchers/equal_to.rs at line 47:
 }
 
 pub fn equal_to<T, D>(expected: T) -> EqualTo<T, D> {
-  EqualTo { expected, marker: PhantomData }
+  EqualTo {
+    expected,
+    marker: PhantomData,
+  }
 }
```

Fix those, get a clean Travis build and this is good to merge!

**Comment by Valloric** [comment]
BTW `has` exists because it works with both a `Result` and an `Option`. It's fine to leave that one alone, we can come back to it later (or leave it not supporting refs).

**Comment by Valloric** [comment]
Merging this, thanks again!

**Comment by Valloric** [comment]
This has now been released as part of 0.2.4. Thanks again!

**Pull request merged**
